pipeline:

  build:
    image: quay.io/ukhomeofficedigital/drone-docker
    commands:
      - docker build -t docker-matomo:$${DRONE_COMMIT_SHA} .
    when:
      event: push

  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - DOCKER_USERNAME
      - DOCKER_PASSWORD
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/docker-matomo
    tags:
      - ${DRONE_BUILD_NUMBER}
      - ${DRONE_COMMIT_SHA}
      - latest
    when:
      branch: master
      event: push

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - DEV_HOSTNAME
      - DEV_KUBE_NAMESPACE
      - DEV_KUBE_SERVER
      - DEV_KUBE_TOKEN
      - DEV_MATOMO_MYSQL_HOST
      - DEV_MATOMO_MYSQL_DBNAME
      - DEV_MATOMO_MYSQL_USER
      - DEV_MATOMO_MYSQL_PASSWORD
      - DEV_MATOMO_MYSQL_PORT
    commands:
      - export HOSTNAME=$${DEV_HOSTNAME}
      - export KUBE_NAMESPACE=$${DEV_KUBE_NAMESPACE}
      - export KUBE_SERVER=$${DEV_KUBE_SERVER}
      - export KUBE_TOKEN=$${DEV_KUBE_TOKEN}
      - export MATOMO_MYSQL_HOST=$${DEV_MATOMO_MYSQL_HOST}
      - export MATOMO_MYSQL_DBNAME=$${DEV_MATOMO_MYSQL_DBNAME}
      - export MATOMO_MYSQL_USER=$${DEV_MATOMO_MYSQL_USER}
      - export MATOMO_MYSQL_PASSWORD=$${DEV_MATOMO_MYSQL_PASSWORD}
      - export MATOMO_MYSQL_PORT=$${DEV_MATOMO_MYSQL_PORT}
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml
      - kd --insecure-skip-tls-verify -f kube/ingress.yml
    when:
      branch: master
      event: push

  deploy_to_staging:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - STAGING_HOSTNAME
      - STAGING_KUBE_NAMESPACE
      - STAGING_KUBE_SERVER
      - STAGING_KUBE_TOKEN
      - STAGING_MATOMO_MYSQL_HOST
      - STAGING_MATOMO_MYSQL_DBNAME
      - STAGING_MATOMO_MYSQL_USER
      - STAGING_MATOMO_MYSQL_PASSWORD
      - STAGING_MATOMO_MYSQL_PORT
    commands:
      - export HOSTNAME=$${STAGING_HOSTNAME}
      - export KUBE_NAMESPACE=$${STAGING_KUBE_NAMESPACE}
      - export KUBE_SERVER=$${STAGING_KUBE_SERVER}
      - export KUBE_TOKEN=$${STAGING_KUBE_TOKEN}
      - export MATOMO_MYSQL_HOST=$${STAGING_MATOMO_MYSQL_HOST}
      - export MATOMO_MYSQL_DBNAME=$${STAGING_MATOMO_MYSQL_DBNAME}
      - export MATOMO_MYSQL_USER=$${STAGING_MATOMO_MYSQL_USER}
      - export MATOMO_MYSQL_PASSWORD=$${STAGING_MATOMO_MYSQL_PASSWORD}
      - export MATOMO_MYSQL_PORT=$${STAGING_MATOMO_MYSQL_PORT}
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml
      - kd --insecure-skip-tls-verify -f kube/ingress.yml
    when:
      branch: deployment
      event: staging

  deploy_to_production:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - PROD_HOSTNAME
      - PROD_KUBE_NAMESPACE
      - PROD_KUBE_SERVER
      - PROD_KUBE_TOKEN
      - PROD_MATOMO_MYSQL_HOST
      - PROD_MATOMO_MYSQL_DBNAME
      - PROD_MATOMO_MYSQL_USER
      - PROD_MATOMO_MYSQL_PASSWORD
      - PROD_MATOMO_MYSQL_PORT
    commands:
      - export HOSTNAME=$${PROD_HOSTNAME}
      - export KUBE_NAMESPACE=$${PROD_KUBE_NAMESPACE}
      - export KUBE_SERVER=$${PROD_KUBE_SERVER}
      - export KUBE_TOKEN=$${PROD_KUBE_TOKEN}
      - export MATOMO_MYSQL_HOST=$${PROD_MATOMO_MYSQL_HOST}
      - export MATOMO_MYSQL_DBNAME=$${PROD_MATOMO_MYSQL_DBNAME}
      - export MATOMO_MYSQL_USER=$${PROD_MATOMO_MYSQL_USER}
      - export MATOMO_MYSQL_PASSWORD=$${PROD_MATOMO_MYSQL_PASSWORD}
      - export MATOMO_MYSQL_PORT=$${PROD_MATOMO_MYSQL_PORT}
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml
      - kd --insecure-skip-tls-verify -f kube/ingress.yml
    when:
      branch: deployment
      event: production
