# Note: This docker compose template is to create matomo and mysql locally along with DB creation (DBSetup.sql). Environment varibles has to update.
version: '3.7'
services:
  mysql:
    image: quay.io/ukhomeofficedigital/mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_HOST=hostname
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpassword
      - MYSQL_DATABASE=mysqldatabase
      - MYSQL_PORT_NUMBER=3306
    volumes:
      - mysql:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  matomo:
    image: quay.io/ukhomeofficedigital/docker-matomo:latest
    container_name: matomo
    environment:
      - MATOMO_HOST=mysql_hostname
      - MATOMO_MYSQL_HOST=matomo_hostname
      - MATOMO_MYSQL_PORT=3306
      - MATOMO_MYSQL_USER=mysqluser
      - MATOMO_MYSQL_PASSWORD=mysqlpassword
      - MATOMO_MYSQL_DBNAME=mysqldatabase
    ports:
      - '9000:9000'
    depends_on:
      - mysql
    volumes:
      - 'matomo:/var/www/html'
volumes:
  mysql:
    driver: local
  matomo:
    driver: local
