---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.MATOMO_NAME}}
spec:
  selector:
    matchLabels:
      app: {{.MATOMO_NAME}}
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: {{.MATOMO_NAME}}
    spec:
      containers:
        - name: matomo
          image: "{{.MATOMO_IMAGE}}:{{.MATOMO_TAG}}"
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            runAsUser: 33
          ports:
            - name: http
              containerPort: {{.MATOMO_PORT}}
              protocol: TCP
          env:
            - name: MATOMO_MYSQL_HOST
              value: {{.MATOMO_MYSQL_HOST}}
            - name: MATOMO_MYSQL_DBNAME
              value: {{.MATOMO_MYSQL_DBNAME}}
            - name: MATOMO_MYSQL_USER
              value: {{.MATOMO_MYSQL_USER}}
            - name: MATOMO_MYSQL_PASSWORD
              value: {{.MATOMO_MYSQL_PASSWORD}}
            - name: MATOMO_MYSQL_PORT
              value: '{{.MATOMO_MYSQL_PORT}}'
            - name: MATOMO_MYSQL_TBL_PREFIX
              value: '{{.MATOMO_MYSQL_TBL_PREFIX}}'
            - name: MATOMO_SALT
              value: '{{.MATOMO_SALT}}'
            - name: MATOMO_URL
              value: '{{.MATOMO_URL}}'
            - name: MATOMO_EMAIL_USER
              value: {{.MATOMO_EMAIL_USER}}
            - name: MATOMO_EMAIL_PASSWORD
              value: {{.MATOMO_EMAIL_PASSWORD}}
            - name: MATOMO_PORT
              value: '{{.MATOMO_PORT}}'

        - name: proxy
          image: "{{.NGINX_IMAGE}}:{{.NGINX_TAG}}"
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
          env:
            - name: PROXY_SERVICE_HOST
              value: 'http://127.0.0.1'
            - name: PROXY_SERVICE_PORT
              value: "{{.MATOMO_PORT}}"
            - name: LOG_FORMAT_NAME
              value: 'json'
            - name: NAXSI_USE_DEFAULT_RULES
              value: 'FALSE'
            - name: ENABLE_UUID_PARAM
              value: 'FALSE'
          ports:
            - name: https
              containerPort: 10443
          volumeMounts:
          - name: certs
            mountPath: /certs
      volumes:
      - name: certs
        secret:
          secretName: "{{.MATOMO_NAME}}-pod-tls"
