---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.MATOMO_NAME}}
spec:
  selector:
    matchLabels:
      app: {{.MATOMO_NAME}}
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: {{.MATOMO_NAME}}
    spec:
      securityContext:
        fsGroup: 33
        runAsNonRoot: true
      containers:
        - name: matomo
          image: "{{.MATOMO_IMAGE}}:{{.MATOMO_TAG}}"
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            runAsUser: 33
          ports:
            - name: http
              containerPort: {{.MATOMO_PORT}}
              protocol: TCP
          env:
            - name: MATOMO_MYSQL_HOST
              value: {{.MATOMO_MYSQL_HOST}}
            - name: MATOMO_MYSQL_DBNAME
              value: {{.MATOMO_MYSQL_DBNAME}}
            - name: MATOMO_MYSQL_USER
              value: {{.MATOMO_MYSQL_USER}}
            - name: MATOMO_MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{.MATOMO_NAME}}"
                  key: mysqlPassword
            - name: MATOMO_MYSQL_PORT
              value: '{{.MATOMO_MYSQL_PORT}}'
            - name: MATOMO_MYSQL_TBL_PREFIX
              value: '{{.MATOMO_MYSQL_TBL_PREFIX}}'
            - name: MATOMO_SALT
              valueFrom:
                secretKeyRef:
                  name: "{{.MATOMO_NAME}}"
                  key: salt
            - name: HOSTNAME
              value: '{{.HOSTNAME}}'
            - name: MATOMO_EMAIL_USER
              value: {{.MATOMO_EMAIL_USER}}
            - name: MATOMO_EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{.MATOMO_NAME}}"
                  key: emailPassword
            - name: MATOMO_PORT
              value: '{{.MATOMO_PORT}}'
          volumeMounts:
            - name: matomo-pvc
              mountPath: /var/www/html/plugins

        - name: {{.MATOMO_NAME}}-proxy
          image: "{{.NGINX_IMAGE}}:{{.NGINX_TAG}}"
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
          env:
            - name: PROXY_SERVICE_HOST
              value: 'http://127.0.0.1'
            - name: PROXY_SERVICE_PORT
              value: "{{.MATOMO_PORT}}"
            - name: LOG_FORMAT_NAME
              value: 'json'
            - name: NAXSI_USE_DEFAULT_RULES
              value: 'FALSE'
            - name: ENABLE_UUID_PARAM
              value: 'FALSE'
            - name: STATSD_METRICS
              value: "FALSE"
            - name: ADD_NGINX_LOCATION_CFG
              value: |
                client_max_body_size      25m;
                add_header                'Access-Control-Allow-Origin' '*';
          ports:
            - name: https
              containerPort: 10443
          volumeMounts:
          - name: certs
            mountPath: /certs
      volumes:
      - name: certs
        secret:
          secretName: "{{.MATOMO_NAME}}-pod-cmio"
      - name: matomo-pvc
        persistentVolumeClaim:
          claimName: "{{.MATOMO_NAME}}-{{.KUBE_NAMESPACE}}"
