---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{.MATOMO_NAME}}-ingress
  labels:
    stable.k8s.psg.io/kcm.class: default
  annotations:
    kubernetes.io/ingress.class: "nginx-external"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/backend-protocol: "HTTPS"
    stable.k8s.psg.io/kcm.provider: http
spec:
  rules:
  - host: {{.HOSTNAME}}
    http:
      paths:
      - backend:
          serviceName: {{.MATOMO_NAME}}-service
          servicePort: 10443
        path: /
  tls:
  - hosts:
      - {{.HOSTNAME}}
    secretName: {{.MATOMO_NAME}}-ingress-cmio
