---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{.MATOMO_NAME}}-ingress
  labels:
    cert-manager.io/solver: http01
  annotations:
    cert-manager.io/enabled: "true"
    kubernetes.io/ingress.class: "nginx-external"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/backend-protocol: "HTTPS"
    ingress.kubernetes.io/proxy-body-size: "25m"
spec:
  rules:
  - host: {{.HOSTNAME}}
    http:
      paths:
      - backend:
          serviceName: {{.MATOMO_NAME}}-service
          servicePort: 10443
        path: /
  tls:
  - hosts:
      - {{.HOSTNAME}}
    secretName: {{.MATOMO_NAME}}-ingress-cmio
