---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-docker-matomo
spec:
  podSelector:
    matchLabels:
      app: docker-matomo
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-external
    ports:
    - protocol: TCP
      port: 10443
