---
apiVersion: v1
kind: Secret
metadata:
  name: "{{.MATOMO_NAME}}"
type: Opaque
data:
  emailPassword: "{{.MATOMO_EMAIL_PASSWORD | b64enc }}"
  mysqlPassword: "{{.MATOMO_MYSQL_PASSWORD | b64enc }}"
  salt: "{{.MATOMO_SALT | b64enc }}"
