---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: docker-matomo
  name: docker-matomo-service
spec:
  ports:
    - name: https
      port: 443
      targetPort: 10443
  selector:
    app: docker-matomo
